databases:
  - name: chat-app
    databaseName: chat_app_4nvo
    user: chat_app_4nvo_user

services:
  - type: web
    name: mychatapp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false